### ISSUE TITLE
Upgrade prisma to latest version

### ISSUE THREAD

**Issue by depombo** [iasql/ecs-fargate-examples#37]
Latest version of prisma changed the API such that it no longer works. This will involve upgrading to whatever API is currently in use.

**Comment by mtp1376** [comment]
So the docs on [this page](https://docs.iasql.com/prisma/) (perhaps along with ECS containers) should be updated, right?

**Comment by depombo** [comment]
This involves getting this PR https://github.com/iasql/ecs-fargate-examples/pull/33 over the finish line. The test for it runs here https://github.com/iasql/iasql-on-iasql/actions/workflows/prisma.yml and it is failing because the API changed.
